// <auto-generated />
using EmployeeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20230719120522_Seeding Employee data")]
    partial class SeedingEmployeedata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Adress = "Delhi",
                            Age = 25,
                            EmailID = "ib@gmail.com",
                            FirstName = "Ishaan",
                            LastName = "Batra"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Adress = "Banglore",
                            Age = 32,
                            EmailID = "ps@gmail.com",
                            FirstName = "Priyanks",
                            LastName = "Singh"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Adress = "Pune",
                            Age = 40,
                            EmailID = "ps@gmail.com",
                            FirstName = "Shweta",
                            LastName = "Agarwal"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Adress = "Pune",
                            Age = 38,
                            EmailID = "dp@gmail.com",
                            FirstName = "Deepa",
                            LastName = "Patel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
